### ISSUE TITLE
Library/Valdosta/APEX_Calculus/6.1/APEX_6.1_59.pg

### ISSUE THREAD

**Issue by WHS-Calculus** [openwebwork/webwork-open-problem-library#1210]
Problem Seed: 222
Students who give the correct answer (with the absolute value) are still getting a hint message to "Make sure to remember the absolute values... " and then they are only receiving half credit as if they didn't include the absolute value.

**Comment by gajennings** [comment]
The file contained some code that attempted to recognize when students entered ln(u) instead of ln(|u|) but it didn't work and I couldn't find a way to make it work reliably. So I just replaced that code with a note in the body of the problem that says student should avoid logs of negative numbers because WeBWorK can't cope with them.  Of course if you use complex numbers then ln(u) is a perfectly correct answer, and ln(|u|) is wrong away from the real number line!
