### ISSUE TITLE
Michigan gateway move broke problem links

### ISSUE THREAD

**Issue by bpaynter** [openwebwork/webwork-open-problem-library#150]
The gateway definition files were moved from OpenProblemLibrary/Michigan/gateways to Contrib/Michigan/gateways. While this is not a problem in itself, the problems that these definitions pointed to were left behind in OpenProblemLibrary. This has broken all of the relative links in the gateway definitions. Either the gateway definitions need to be moved back, or the problems need to be brought with them, or the links need to be updated.

**Comment by jwj61** [comment]
They were moved because of a complaint that they did not work as is.  A secondary complaint was that the OPL generally does not provide set definition files.  

They don't work out of the box since they have paths such as ../../../problembanks/gateways/integral/topic_logarithms/prob73.pg
and there is no directory problembanks in the OPL.  To make it work, one would have to create a directory link, move files around, or edit these files.  With them moved, one has the same options.

The initial suggestion was to just delete them all.  I thought it was better to move them to Contrib where people could find them (and edit them to suit their needs), or at least see an example of a set definition file for a gateway.

**Comment by bpaynter** [comment]
No problem. I was just confused when I came across them because I assumed I had a permissions issue. Perhaps this could be as simple as including the information you just sent as a README in Contrib/Michigan/gateway?

**Comment by jwj61** [comment]
Good idea.
