### ISSUE TITLE
Wrong basis in Hope/Multi1/04-02-Kernel-image/Ker_im_03.pg

### ISSUE THREAD

**Issue by heiderich** [openwebwork/webwork-open-problem-library#403]
Problem `OpenProblemLibrary/Hope/Multi1/04-02-Kernel-image/Ker_im_03.pg` accepts the zero vector as the correct answer for the kernel. However the kernel is the vector space that only consists of the zero vector, which has the empty set as a basis and not the zero vector.

I tried to change the line 

    $kernel = List($k1);

to

    $kernel = List();

This leads to the following error:

```
        Problem1
1. ERROR caught by Translator while processing problem file:Library/Hope/Multi1/04-02-Kernel-image/Ker_im_03.pg
****************
ERRORS from evaluating PG file: 
 'HASH' is not defined in this context; see position 1 of formula at line 91 of (eval 1273)
```

**Comment by jwj61** [comment]
Fixed.  Added an instruction to use 'none' in place of the list of vectors if it is empty, and set the correct answer to 'none'.

**Comment by heiderich** [comment]
Just for reference: This was fixed in decd3880df623ffadf9e6e16cc13344cd38ed7a3. 

Would it be possible to extend `List` to be able to deal with empty lists? I think it would be more natural to submit an empty list rather than 'none'.

**Comment by jwj61** [comment]
Based on the documentation, I thought that it should be able to accept '()' via List('()'), but that didn't work.  Maybe I did it wrong, or maybe it is a bug in mathobjects (@dpvc).

But, I think students would find that more confusing.  My own first choice would be the string 'empty', but I could not get that to work.  Someone who is better with mathobjects might be able to get one of those things to work.

**Comment by dpvc** [comment]
I've made a pull request that fixes the error message you are getting about hash being undefined.

> Would it be possible to extend `List` to be able to deal with empty lists?

They should have already worked, and after the PR, should again.  But note that there are some caveats for dealing with lists, and empty lists in particular, but also singleton lists, and lists of lists.  MathObjects has some heuristics for dealing with these, but they are not appropriate for all situations.  There are flags that control the finer points, when needed.

If by "deal with empty lists" you mean you would like the student to be able to leave an entry box blank, that is generally a bad idea.  For one thing, WeBWorK doesn't process blank answers by default, so you would need to remove the blank answer filter.  But more importantly, it is hard to print or display the correct or student answer when it is blank, and that can lead to student confusion.  It is alway better to require *some* form of response that can be displayed and checked.

In MathObjects, list-like object (such as vectors) have delimiters (e.g., `<` and `>`).  There are two ways to create any MathObject: either via an explicit constructor, like `Vector(1,2,3)`, or by parsing a string, like `Compute("<1,2,3>")`.  When a constructor is used, the delimiters are not given explicitly, so are taken from the Context's defaults for the object type.  So `Vector(1,2,3)` gets implicit angle bracket delimiters from the context, while `Compute("<1,2,3>")` get them explicitly from the string.

Things are a little more complicated for lists, because we want students to be able to enter lists like `1,2,3` without delimiters; but there are also cases where you want to be able to enter lists explicitly with delimiters.  E.g., `(1, MAX), (-3, MIN)` might be a list of lists of *x*-values and an indication of whether that *x* is a maximum or a minimum of a given function.  So here, parentheses are important in grouping the sublist items.  So we need to deal with lists that have delimiters as well as those that don't.

This leads to a difficulty, however.  Should a student answer of `(1,2,3)` match `List(1,2,3)`?  That is, does a student answer of `(1,2,3)` represent a list of there elements, 1, 2, and 3, or is it a list of one element, the list (1,2,3)?  There are flags that control how this is interpreted.  The `implicitList` flag determines whether a single element is turned into a list consisting of that one element.  For example, with `List(1,2,3)->cmp(implicitList=>0)`, an answer of `(1,2,3)` will be considered a list of three elements (the numbers 1, 2, and 3) with explicit parentheses, whereas with `List(1,2,3)->cmp(implicitList=>1)`, the answer `(1,2,3)` will be considered a list of one element (the list `(1,2,3)`) with no delimiters.  The default for `implicitList` is 1, so singletons are turned into lists automatically.

In neither case above would the answer `(1,2,3)` be marked correct.  In the first case, the reason is that the student answer has explicit parentheses, while the correct answer has no parentheses, so the two lists don't match because of that.  In the second case, the student's list as a list of one item (that item being a list), while the correct answer is a list of three numbers.  Both of these could be made to mark the answer `(1,2,3)` correct, if you wanted.  For the first, the issue is the matching of the parentheses, and there is a flag, `requireParenMatch`, that controls whether that is required or not.  It is true by default, but `List(1,2,3)->cmp(implicitList=>0,requireParenMatch=>0)` would allow the student answer `(1,2,3)` to be treated as correct (as well as '1,2,3').  On the other hand, using `List("(1,2,3)")` rather than `List(1,2,3)` in the second example would make a list of one item (that being a list), and so the student answer `(1,2,3)` would be correct using the default values of `implicitList` and `requireParenMatch`.

Note that `List("(1,2,3)")` and `Compute("(1,2,3)")` produce different things:  the first is a list of lists (and it has no delimiters), while the latter is a list of three numbers that has parentheses as explicit delimiters.  Unfortunately, there is no way to produce `List("(1,2,3)")` using `Compute()`, though you can get the same effect as `Compute("(1,2,3)")` using `List(1,2,3)->with(open=>"(",close=>")")`.

Because lists are used most frequently without delimiters in student answers (e.g., `1,2,3`), delimiters are removed by default from the current answer.  (This is due mostly to some historical factors, namely the `List(1,2,3)` used to add parentheses as delimiters, automatically, rather than using no delimiters as it currently does.)  As with the other situations, there is a flag that controls this: `removeParens`.  When set to 1 (the default), `Compute("(1,2,3)")->cmp` will be treated as `List(1,2,3)->cmp` by having its parentheses removed automatically, so the student answer of `1,2,3` would be marked correct (and `(1,2,3)` would be incorrect).  On the other hand `Compute("(1,2,3)")->cmp(removeParens=>0, implicitList=>0)` would do the reverse:  `(1,2,3)` is marked correct, and `1,2,3` is incorrect, since the delimiters don't match.  (The default value for this flag probably should be 0 rather than 1, but it is probably too late to change that now.)

By default, lists entries can be in any order, so `List(1,2,3)->cmp` could be entered as `2,1,3` or `3,2,1` by a student and still be marked correct.  But sublists are *ordered* lists, so `List("(1,2,3)")->cmp` would require `(1,2,3)` as the answer, not `(2,1,3)` or any of the other permutations.  When you use `List(1,2,3)->cmp(implicitList=>0,requireParenMatch=>0)`, this is still an unordered list, so while `(1,2,3)` would be accepted, so would `(2,1,3)` or `(3,2,1)`.  The `ordered` flag controls this behavior.  So `List(1,2,3)->cmp(implicitList=>0,requireParenMatch=>0,ordered=>0)`, would only accept `(1,2,3)` as correct.

In summary:

* `implicitList` controls whether an answer of a single parenthesis-delimited list is treated as a list consisting of that one item, or as the list itself. (Default is 1.)

* `requireParenMatch` controls whether the delimiters for the student answer must match those of the correct answer or not. (Default is 1.)

* `removeParens` controls whether delimiters are removed from the correct answer before checking. (Default is 1.)

* `ordered` controls whether the student answer can be in any order, or must be in the same order as the correct one. (Default is 0, so unordered.)

What does this have to do with the empty set?  John Jones is correct that the empty set is represented as `()`.  But by default, a single list is turned into a list of lists (by `implicitList=>1`), and parentheses must match (by `requireParenMatch=>1`), so `List()->cmp` will not mark `()` as correct for both those reasons.  In order to allow `()` to be marked correct, you need to use `List()->cmp(implicitList=>0,requireParenMatch=>0)`.  I suppose it would be possible to make the default be `implicitList=>0,requireParenMatch=>0` for empty lists, but that isn't currently the case.

If you want `empty` to be what you enter for an empty list rather than `()`, you can use

```
Context()->constants->add(empty=>List()->with(open=>"",close=>""));
```

and then `List()->cmp` will accept `empty` as correct (as well as `()`).

Finally, if you are using an empty list, MathObjects doesn't know the type of object that could appear in the list, so defaults to numbers.  If the list could contain something other than numbers (e.g., vectors, as in this case), you need to tell the list checker that so that it does the proper type checking on the student answers when their list *isn't* empty.  I.e., use `List()->cmp(typeMatch=>Vector(1,2,3))` to indicate an empty list of vectors (as opposed to `List()->cmp`, which is an empty list of numbers).

I hope the helps you understand the situation and makes it possible for you to handle the lists in the way you need.

**Comment by dpvc** [comment]
@jwj61, I made a comment in the pull request cited above, but since it is merged already, I'm not sure if you will receive a notification about it.  It suggests the use of `typeMatch` for your answer of `NONE`, since without that, students who enter vectors will get an error message indicating that their answer is a vector not a number, which would be confusing to them.

**Comment by jwj61** [comment]
Thanks.  I had seen the various comments on git (I get anything for webwork2, pg, or the OPL) -- I just hadn't gotten around to acting on it.  I now have the problem working as desired, thanks.

**Comment by dpvc** [comment]
OK, great.  I just wasn't sure if closed PRs would generate notices.
