### ISSUE TITLE
draggable proof not working (can't drag) (macros/MC/draggableProof.pl)

### ISSUE THREAD

**Issue by jirilebl** [openwebwork/webwork-open-problem-library#622]
I'm running on 2.14, trying problems like MC/Proofs/DirectProofs/EpsilonDeltaLimit.pg I can't get the dragging to work.  When I install the older version of the macro (pre-January) then it works, though it is a bit glitchy.  I don't have a 2.15 installation to try it on.

The issues seems to be that I don't have jquery.nestable.js ...

However, I can't find this js file anywhere on the webwork github.  I suppose it should be in webwork2/htdocs/js but it is not, even in the current master.

So I'd suppose the current draggable proofs problems do not work on any standard installation of webwork.

**Comment by lahvak** [comment]
You have to install `jquery.nestable.js` in the course directory for any course that uses draggable proofs, as described at http://webwork.maa.org/moodle/mod/forum/discuss.php?d=4335

That is definitely not optimal.  Since the draggable proofs problems are in the OPL, the necessary javascript should be included with WeBWorK.

**Comment by drdrew42** [comment]
This has been resolved with the latest release of WeBWorK 2.16 (see openwebwork/webwork2#1259)
