### ISSUE TITLE
Rounding issue

### ISSUE THREAD

**Issue by kitsook** [openwebwork/webwork-open-problem-library#665]
There seems to be a rounding issue with the question WHFreeman/Rogawski_Calculus_Early_Transcendentals_Second_Edition/9_Introduction_to_Differential_Equations/9.3_Graphical_and_Numerical_Methods/9.3.14.pg

The student was assigned the seed 4761.  For part (c) `|y(0.2) - y1|`, WeBWorK expected the answer to be 0.00298094.  Student answered 0.00298277 and is considered incorrect.

Not familiar with the Perl script used in webwork, but is there a way to allow some sort of % of error for rounding?

**Comment by jwj61** [comment]
Webwork problems can control the amount of error.  In some cases, the error is an absolute difference, but usually it is relative to the correct answer.  Here, the student's answer differs in the 4th significant digit and generally, that is not close enough.

Typically, a course starts with a set which introduces the student to webwork, and one of the items should point out how many significant digits the student should provide (unless the problem says otherwise).
