### ISSUE TITLE
Several chapters deleted from computer graphics text

### ISSUE THREAD

**Issue by nathancarter** [openwebwork/webwork-open-problem-library#895]
In 2018, I contributed 187 problems from a text I wrote on the mathematics of computer graphics.  These included chapters 2 through 15 of the text.

 * Here is [the commit](https://github.com/openwebwork/webwork-open-problem-library/commit/b3e0afa6246411e52994beb2e1789d0ea7dca6d2#diff-0a60d5ad86e1a59ba259af7551b288d4aded8aab9bf93a46cbb12d126bbf65b7).
 * Here is [the folder](https://github.com/openwebwork/webwork-open-problem-library/tree/b3e0afa6246411e52994beb2e1789d0ea7dca6d2/OpenProblemLibrary/BentleyUniversity/MathematicsOfComputerGraphics) at the time of committing.

Today, chapters 9, 11, 13, and 14 have been deleted.  I'm not sure why.  There seem to have been a bunch of changes to that folder, but I was not CCed on the issues, pulls, etc., so I did not know they were happening.

 * Here is the [full history](https://github.com/openwebwork/webwork-open-problem-library/commits/master/OpenProblemLibrary/BentleyUniversity/MathematicsOfComputerGraphics) of the folder on GitHub.
 * Here is the [current content](https://github.com/openwebwork/webwork-open-problem-library/tree/master/OpenProblemLibrary/BentleyUniversity/MathematicsOfComputerGraphics) of the folder.

It seems most of the files were removed as part of a huge process that @jwj61 did across many folders, and that the same process also put most of the files back, but not all.  This also happened in 2018, which is rather confusing, because I've used the full course on an MAA WeBWorK server in 2021 and had access to all the chapters...not sure how that happened, unless perhaps if the MAA server was using an old version of the repository.

Can anyone shed light on this, and let me know the appropriate process for reinstating the deleted problems?  Thanks!

**Comment by nathancarter** [comment]
OK.  Is there something I should to do find out the reasons for the not (yet?) accepted problems?  Then I could fix/improve them to get them "in."  Thanks.

**Comment by nathancarter** [comment]
I would like to use these problems in a course this fall.  @jwj61 was the original one to process them.  Can you help me know what I should do to get the problems into a form that can be accepted into the OPL?  Thanks!

**Comment by drdrew42** [comment]
Problems from contrib are now available in the new version of WeBWorK (2.17) after running OPL-update. In order for contrib problems to appear in the Library Browser, your course must have a `Contrib/` link in the templates directory (similar to `Library/`).

As far as accepting problems into the OPL goes -- that was work that was funded back in 2018, and we (The WeBWorK Project organization) are working on what to do moving forward. The process involved many reviewers, although John Jones was the lead on that project, so that is why the commits are under his account. I wasn't a part of that process, so I'm afraid I cannot be more specific regarding the rationale behind why some chapters/problems were accepted while others were not.

Understanding that this is a frustration for many contributors, I have made changes in the latest version of WeBWorK to bring problems from Contrib into the Library Browser. In the absence of funding to organize an effort to review and accept more problems in the OPL, this is the best I could figure out for addressing this issue expediently.

Just to check, I've looked briefly at the problems in Contrib from chapter 9. Here's my best guess at why some of these problems may have been rejected:
- reliance on / references to 'POV' software
- references to chapter 9 in a textbook
- problems not tagged with official taxonomy

Again, this is just my very quick read and should not be interpreted as actual reasons why we are where we are. Your contributions are certainly appreciated, and content that you've shared was accepted according to the guidelines set out by the OPL team back in the summer of 2018. Those that didn't make it are now available through the library browser, and perhaps this content will be revisited again in the future.

If you have any questions or run into issues finding your content in the library browser (in WeBWorK 2.17), please let me know -- or post on the forums.

**Comment by nathancarter** [comment]
That's very helpful, thanks.  I didn't know that 2018 was sort of a year of funded intensity in the OPL space.  Are there instructions anywhere for setting up the link you refer to above?  On the one hand, I'm familiar with making links from, say, a command prompt, but I'm not sure, if I'm getting WeBWorK hosting from an online source, if I'll have access to drop to a shell prompt and modify the filesystem.  Is there an inside-the-WeBWorK-UI way to do this?

**Comment by drdrew42** [comment]
To clarify, it wasn't just 2018, but there was a period of time where WeBWorK had received significant grant funding to run focused work on reviewing / curating OPL content.

And yes, I'm talking about sym-linking from your course's templates directory: `ln -s /opt/webwork/libraries/webwork-open-problem-library/Contrib Contrib`

I would ask your hosting service about this. They might do it for you, rather than providing command-line access directly.
